export default {
  useCustomProperties: true,
  initialColorMode: "system",
  colors: {
    text: "#293241",
    background: "#E0FBFC",
    primary: "#EE6C4D",
    secondary: "#98C1D9",
    highlight: "#EE6C4D",
    accent: "#e8907a",
    muted: "#3e4c6c",
    gray: "#D0D0DD",
    notion_callout_default: "rgba(235, 236, 237, 0.3)",
    notion_callout_gray: "rgb(241, 241, 239)",
    notion_callout_brown: "rgb(244, 238, 238)",
    notion_callout_orange: "rgb(251, 236, 221)",
    notion_callout_yellow: "rgb(251, 243, 219)",
    notion_callout_green: "rgb(237, 243, 236)",
    notion_callout_blue: "rgb(231, 243, 248)",
    notion_callout_purple: "rgb(244, 240, 247)",
    notion_callout_pink: "rgb(249, 238, 243)",
    notion_callout_red: "rgb(253, 235, 236)",
    modes: {
      dark: {
        text: "#E0FBFC",
        background: "#293241",
        primary: "#EE6C4D",
        secondary: "#3D5A80",
        muted: "#D0D0DD",
        highlight: "#fecb0a",
        gray: "#D0D0DD",
        accent: "#e8907a",
        notion_callout_default: "rgba(64, 64, 64, 0.3)",
        notion_callout_gray: "rgb(41, 41, 39)",
        notion_callout_brown: "rgb(44, 38, 38)",
        notion_callout_orange: "rgb(51, 36, 21)",
        notion_callout_yellow: "rgb(51, 43, 19)",
        notion_callout_green: "rgb(37, 43, 36)",
        notion_callout_blue: "rgb(31, 43, 48)",
        notion_callout_purple: "rgb(44, 40, 47)",
        notion_callout_pink: "rgb(49, 38, 43)",
        notion_callout_red: "rgb(53, 35, 36)",
      },
    },
  },
  fonts: {
    body: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
    heading: "inherit",
    monospace: "Menlo, monospace",
  },
  fontSizes: [12, 14, 16, 20, 24, 32, 48, 64, 72],
  fontWeights: {
    body: 400,
    heading: 700,
    display: 900,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.25,
  },
  textStyles: {
    heading: {
      fontFamily: "heading",
      fontWeight: "heading",
      lineHeight: "heading",
    },
    display: {
      variant: "textStyles.heading",
      fontSize: [5, 6],
      fontWeight: "display",
      letterSpacing: "-0.03em",
      mt: 3,
    },
  },
  styles: {
    Container: {
      p: 3,
      maxWidth: 1024,
    },
    root: {
      fontFamily: "body",
      lineHeight: "body",
      fontWeight: "body",
    },
    h1: {
      variant: "textStyles.display",
    },
    h2: {
      variant: "textStyles.heading",
      fontSize: 5,
    },
    h3: {
      variant: "textStyles.heading",
      fontSize: 4,
    },
    h4: {
      variant: "textStyles.heading",
      fontSize: 3,
    },
    h5: {
      variant: "textStyles.heading",
      fontSize: 2,
    },
    h6: {
      variant: "textStyles.heading",
      fontSize: 1,
    },
    a: {
      color: "primary",
      textDecoration: "underline",
      textDecorationStyle: "wavy",
      ":hover": {
        color: "secondary",
        cursor: "pointer",
      },
    },
    pre: {
      fontFamily: "monospace",
      fontSize: 1,
      p: 3,
      color: "text",
      bg: "muted",
      overflow: "auto",
      code: {
        color: "inherit",
      },
    },
    code: {
      fontFamily: "monospace",
      fontSize: 1,
    },
    inlineCode: {
      fontFamily: "monospace",
      color: "secondary",
      bg: "muted",
    },
    table: {
      width: "100%",
      my: 4,
      borderCollapse: "separate",
      borderSpacing: 0,
      "th,td": {
        textAlign: "left",
        py: "4px",
        pr: "4px",
        pl: 0,
        borderColor: "muted",
        borderBottomStyle: "solid",
      },
    },
    th: {
      verticalAlign: "bottom",
      borderBottomWidth: "2px",
    },
    td: {
      verticalAlign: "top",
      borderBottomWidth: "1px",
    },
    hr: {
      border: 0,
      borderBottom: "1px solid",
      borderColor: "muted",
    },
  },
};
